spaced:
  precalculus:
    authors:
    - Stewart
    - Redlin
    - Watson
    book: Precalculus, Mathematics for Calculus
    data: precalc.csv
    goal: Complete the precalculus textbook by my next birthday
